import { defineCollection, z } from 'astro:content';

const newsCollection = defineCollection({
  type: 'content',
  schema: ({ image }) => z.object({
    title: z.string(),
    excerpt: z.string().optional(), // Auto-generated by Astro components
    publishDate: z.coerce.date(),
    featuredImage: image().optional().or(z.string().optional()),
    category: z.enum([
      '過往活動',
      '文章',
      '最新消息',
      '資助申請',
      '比賽',
      '課程',
      'AI人工智能課程',
      '其他'
    ]).default('過往活動'),
    tags: z.array(z.string()).optional(),
    author: z.string().default('admin'),
    isFeatured: z.boolean().default(false),
    externalLink: z.string().url().optional(),
    wpSlug: z.string().optional(),
    wpDate: z.string().optional(),
    readingTime: z.number().optional(),
  }),
});

const primaryCompetitionsCollection = defineCollection({
  type: 'data',
  schema: z.object({
    date: z.string(),
    name: z.string(),
    keywords: z.string(),
    popularity: z.string(),
    link: z.string(),
    level: z.enum(['小學', '中學', '中小學']).default('小學'),
  }),
});

const secondaryCompetitionsCollection = defineCollection({
  type: 'data',
  schema: z.object({
    date: z.string(),
    name: z.string(),
    keywords: z.string(),
    popularity: z.string(),
    link: z.string(),
    level: z.enum(['小學', '中學', '中小學']).default('中學'),
  }),
});

export const collections = {
  'news': newsCollection,
  'primary-competitions': primaryCompetitionsCollection,
  'secondary-competitions': secondaryCompetitionsCollection,
}; 